//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModel
{
	/// <summary>
	/// Database       : dd
	/// Data Source    : tcp://localhost:5920
	/// Server Version : 15.4
	/// </summary>
	public partial class Connection : LinqToDB.LinqToDBConnection
	{
		public ITable<dd> dd { get { return this.GetTable<dd>(); } }

		partial void InitMappingSchema()
		{
		}

		public Connection()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public Connection(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public Connection(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public Connection(DataOptions<Connection> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="public", Name="dd")]
	public partial class dd
	{
		[PrimaryKey, NotNull    ] public string   gid      { get; set; } // text
		[Column,        Nullable] public string   dd2      { get; set; } // text
		[Column,        Nullable] public string   ddColumn { get; set; } // text
		[Column,        Nullable] public string[] dd3      { get; set; } // text[]
	}

	public static partial class TableExtensions
	{
		public static dd Find(this ITable<dd> table, string gid)
		{
			return table.FirstOrDefault(t =>
				t.gid == gid);
		}
	}
}
