//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModel
{
	/// <summary>
	/// Database       : dd
	/// Data Source    : tcp://192.168.1.121:5920
	/// Server Version : 10.11
	/// </summary>
	public partial class Connection : LinqToDB.LinqToDBConnection
	{
		public ITable<dd> dd { get { return this.GetTable<dd>(); } }

		partial void InitMappingSchema()
		{
		}

		public Connection()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public Connection(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="public", Name="dd")]
	public partial class dd
	{
		[Column("dd"), Nullable] public string ddColumn { get; set; } // character varying(255)
		[Column(),     Nullable] public string dd2      { get; set; } // character varying(255)
	}
}

#pragma warning restore 1591
